export const ENTRY_LIST_REQUEST = "ENTRY_LIST_REQUEST";
export const ENTRY_LIST_SUCCESS = "ENTRY_LIST_SUCCESS";
export const ENTRY_CATEGORY_LIST_SUCCESS = "ENTRY_CATEGORY_LIST_SUCCESS";
export const ENTRY_LIST_FAIL = "ENTRY_LIST_FAIL";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const ENTRY_DETAILS_REQUEST = "ENTRY_DETAILS_REQUEST";
export const ENTRY_DETAILS_SUCCESS = "ENTRY_DETAILS_SUCCESS";
export const ENTRY_DETAILS_FAIL = "ENTRY_DETAILS_FAIL";

export const ENTRY_UPDATE_REQUEST = "ENTRY_UPDATE_REQUEST";
export const ENTRY_UPDATE_SUCCESS = "ENTRY_UPDATE_SUCCESS";
export const ENTRY_UPDATE_FAIL = "ENTRY_UPDATE_FAIL";
export const ENTRY_UPDATE_RESET = "ENTRY_UPDATE_RESET";

export const SUBSCRIPTION_LIST_REQUEST = "SUBSCRIPTION_LIST_REQUEST";
export const SUBSCRIPTION_LIST_SUCCESS = "SUBSCRIPTION_LIST_SUCCESS";
export const SUBSCRIPTION_CREATE_SUCCESS = "SUBSCRIPTION_CREATE_SUCCESS";
export const SUBSCRIPTION_UPDATE_SUCCESS = "SUBSCRIPTION_UPDATE_SUCCESS";
export const SUBSCRIPTION_DELETE_SUCCESS = "SUBSCRIPTION_DELETE_SUCCESS";
export const SUBSCRIPTION_LIST_FAIL = "SUBSCRIPTION_LIST_FAIL";
